/* MMM-EarthquakeMonitorJP — Preview fixtures
 *
 * Test payloads are generated by the module itself (`buildTestPayload`),
 * so the preview and the in-situ test mode always exercise identical data.
 * This file only exposes the scenario list for building the preview UI.
 */

/* eslint-disable no-unused-vars */
const PreviewFixtures = (() => {

  /**
   * Read the scenario catalogue straight off the registered module
   * definition, so new scenarios appear in the preview automatically.
   */
  function scenarioList() {
    const def = window.Module &&
      window.Module.definitions &&
      window.Module.definitions["MMM-EarthquakeMonitorJP"];

    if (!def || !def.testScenarios) return [];

    return Object.keys(def.testScenarios).map((name) => {
      const s = def.testScenarios[name];
      return {
        name: name,
        key: s.key,
        label: s.label,
        code: s.code,
        scale: s.scale,
        stale: !!s.ageSec,
        cancelled: !!s.cancelled,
      };
    });
  }

  // Group the scenarios for a tidier control panel
  function grouped() {
    const list = scenarioList();
    return {
      quake: list.filter((s) => s.code === 551),
      eew: list.filter((s) => s.code === 556),
      tsunami: list.filter((s) => s.code === 552),
    };
  }

  return { scenarioList, grouped };
})();
